#!/usr/bin/env python
"""Run SOC Platform Agent."""
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

if __name__ == "__main__":  # pylint: disable=import-error
    from agent.agent import main  # pylint: disable=import-error
    main()