#!/usr/bin/env python
"""Run PCAP Analyzer."""
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

if __name__ == "__main__":
    from pcap.pcap_analyzer import main
    main()