"""Patrones de deteccion para diferentes fuentes de log."""
from .auth import (
    AUTH_LOG_PATTERNS,
    IPTABLES_PATTERNS,
    SURICATA_PATTERNS,
    AUTH_TIMESTAMP_PATTERN,
    extract_timestamp_from_log,
    format_log_timestamp,
    get_patterns_for_source,
    get_risk_weight,
    determine_severity,
    EVENT_WEIGHTS,
    ATTACK_SEVERITY,
)
from .web import (
    WEB_LOG_PATTERNS,
    APACHE_ACCESS_PATTERN,
    NGINX_ACCESS_PATTERN,
    parse_apache_access_log,
    parse_nginx_access_log,
    check_injection_patterns,
    get_risk_weight as web_get_risk_weight,
    extract_timestamp_from_log as web_extract_timestamp,
)

__all__ = [
    "AUTH_LOG_PATTERNS",
    "IPTABLES_PATTERNS",
    "SURICATA_PATTERNS",
    "AUTH_TIMESTAMP_PATTERN",
    "WEB_LOG_PATTERNS",
    "APACHE_ACCESS_PATTERN",
    "NGINX_ACCESS_PATTERN",
    "extract_timestamp_from_log",
    "format_log_timestamp",
    "web_extract_timestamp",
    "get_patterns_for_source",
    "get_risk_weight",
    "determine_severity",
    "web_get_risk_weight",
    "parse_apache_access_log",
    "parse_nginx_access_log",
    "check_injection_patterns",
    "EVENT_WEIGHTS",
    "ATTACK_SEVERITY",
]
